twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_name: 'WatchedS'
        year_of_site_creation: '2018'
        GOOGLE_RECAPTCHA_SITE_KEY: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        GOOGLE_RECAPTCHA_SECRET: '%env(GOOGLE_RECAPTCHA_SECRET)%'
        omdbapikey: '%env(omdbapikey)%'